# Generated by Django 2.2.8 on 2020-05-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is test description and QQ is real cute.'),
            preserve_default=False,
        ),
    ]
